server:
  port: 8086
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/postgres} # Добавить в переменные окружения при помощи url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/post_info}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create


